# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 15 May 2011 13:45:27 +0000
*	@ALL	8
conf:template	@user	2
conf:template	@ALL	0
