<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: kosenconf
 * Date: Sun, 15 May 2011 23:28:30 +0900
 */

$conf['title'] = '高専カンファレンス';
$conf['start'] = 'index';
$conf['lang'] = 'ja';
$conf['template'] = 'kcweb';
$conf['license'] = 'cc-by-sa';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['relnofollow'] = 0;
$conf['indexdelay'] = 5;
$conf['mailguard'] = 'visible';
$conf['useslash'] = 1;

// end auto-generated content
